version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laptop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: your_db
      DB_USER: your_user
      DB_PASSWORD: your_password
    depends_on:
      - db
    ports:
      - "5000:5000"  # Este puerto solo se usa si tu aplicación expone un endpoint web

volumes:
  postgres_data: