from telegram.ext import ConversationHandler


MENU = chr(0)
ADD = chr(1)
SHOW = chr(2)
DELETE = chr(3)
ADD_PERIODIC = chr(4)
LISTENING_REMINDER = chr(5)
LISTENING_PERIODIC_REMINDER = chr(6)
SHOW_ALL = chr(7)
SHOW_TODAY = chr(8)
SHOW_TOMORROW = chr(9)
SHOW_WEEK = chr(10)
SHOW_BY_NAME = chr(11)
LISTENING_TO_SHOW_BY_NAME = chr(12)
DELETE_ALL = chr(13)
DELETE_BY_NAME = chr(14)
CONFIRM_DELETE_ALL = chr(15)
CONFIRMED_DELETE_ALL = chr(16)
LISTENING_TO_DELETE_BY_NAME = chr(17)
CONFIRM_DELETE_BY_NAME = chr(18)
CONFIRMED_DELETE_BY_NAME = chr(19)
START_OVER = chr(20)
START_WITH_NEW_REPLY = chr(21)
STOPPING = chr(22)

END = ConversationHandler.END